# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec8bb2603061037e685721a1528e551558ce3bb823b8bbf48aa8fdece77fdee9ff09e35c92bc5de1e893454c09475cfabd9cacc328451b430ff4fe8398bcfdc7

test:
  secret_key_base: 47c55ce773f29411e7e3ad0f212856774545d3d239f1da50e3057b8f780f940b80827403e228e532b766e8cc9526ee62cd46b5b6f1f4f6ab7ad970f632e664d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
